name: build-prose-mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from git repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Show go version
        run: go version

      - name: Print working directory
        run: pwd

      - name: Build
        run: go build ./prose

      - name: Run unit tests
        run: go test ./prose -v

      - name: Generate coverage report
        run: |
          go test ./prose -v -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          verbose: true # optional (default = false)