name: build-prose-mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from git repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Show go version
        run: go version

      - name: Print working directory
        run: pwd

      - name: Build
        run: go build ./prose

      - name: Run unit tests and generate coverage report
        run: go test ./prose -v -coverprofile=coverage.xml -covermode=atomic